spring.application.name=hospital-management-system


server.port=8081

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=lALESWAR@28
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode =always
spring.sql.init.data-locations=classpath:data.sql


security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=3600000